version: 0.2

env:
  secrets-manager:
    DOCKER_USER: ${SECRETS_MANAGER_ARN}:DOCKER_USER
    DOCKER_TOKEN: ${SECRETS_MANAGER_ARN}:DOCKER_TOKEN

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version

      # login to Elastic container registry
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  pre_build:
    commands:
      - echo 'Start pre_build phase'
      - yarn -v
      - node --version

  build:
    commands:
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t $IMAGE_REPO -f ./deployment/ecs/Dockerfile . --no-cache
      - docker tag $IMAGE_REPO:latest $REPOSITORY_URI:latest
      - docker tag $IMAGE_REPO:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - sed -ie "s@__CONTAINER_NAME__@$CONTAINER_NAME@" appspec.yml
      - sed -ie "s@__CONTAINER_PORT__@$CONTAINER_PORT@" appspec.yml
      - cp taskdef-template.json $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__CONTAINER_NAME__@$CONTAINER_NAME@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__CONTAINER_PORT__@$CONTAINER_PORT@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__TASK_DEFINITION_FAMILY__@$TASK_DEFINITION_FAMILY@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__AWS_REGION__@$AWS_REGION@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__ECR_IMAGE__@$REPOSITORY_URI:$IMAGE_TAG@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__LOG_GROUP__@$LOG_GROUP@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__TASK_ROLE__@$TASK_EXECUTION_ROLE@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__EXECUTION_ROLE__@$TASK_EXECUTION_ROLE@" $TASK_DEFINITION_FILE_NAME

artifacts:
  files:
    - appspec.yml
    - taskdef.json
