version: 0.2

env:
  secrets-manager:
    EMPLOYEE_SECRETS: ${BUILDTIME_SECRETS_MANAGER_ARN}:main

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version

      # login to Elastic container registry
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  pre_build:
    commands:
      - echo 'Start pre_build phase'
      - yarn -v
      - node --version
      - export BUILD_SECRETS=$EMPLOYEE_SECRETS
      - TASK_DEFINITION_FAMILY=$(echo $BUILD_SECRETS | jq -r '.TASK_DEFINITION_FAMILY')
      - ECR_URI=$(echo $BUILD_SECRETS | jq -r '.ECR_URI')
      - IMAGE_REPO=$(echo $BUILD_SECRETS | jq -r '.IMAGE_REPO')
      - LOG_GROUP=$(echo $BUILD_SECRETS | jq -r '.LOG_GROUP')
      - TASK_DEFINITION_FILE_NAME=$(echo $BUILD_SECRETS | jq -r '.TASK_DEFINITION_FILE_NAME')
      - CONTAINER_NAME=$(echo $BUILD_SECRETS | jq -r '.CONTAINER_NAME')
      - TASK_EXECUTION_CPU=$(echo $BUILD_SECRETS | jq -r '.TASK_EXECUTION_CPU')
      - TASK_EXECUTION_MEMORY=$(echo $BUILD_SECRETS | jq -r '.TASK_EXECUTION_MEMORY')
      - APP_SPEC_FILE_NAME=$(echo $BUILD_SECRETS | jq -r '.APP_SPEC_FILE_NAME')
      - CONTAINER_PORT=$(echo $BUILD_SECRETS | jq -r '.CONTAINER_PORT')

  build:
    commands:
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t $IMAGE_REPO -f ./deployment/ecs/Dockerfile . --no-cache
      - docker tag $IMAGE_REPO:latest $ECR_URI:latest
      - docker tag $IMAGE_REPO:latest $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - docker push $ECR_URI:latest
      - docker push $ECR_URI:$IMAGE_TAG
      - sed -ie "s@__CONTAINER_NAME__@$CONTAINER_NAME@" $APP_SPEC_FILE_NAME
      - sed -ie "s@__CONTAINER_PORT__@$CONTAINER_PORT@" $APP_SPEC_FILE_NAME
      - cp taskdef-template.json $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__CONTAINER_NAME__@$CONTAINER_NAME@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@\"__CONTAINER_PORT__\"@$CONTAINER_PORT@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__TASK_DEFINITION_FAMILY__@$TASK_DEFINITION_FAMILY@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__AWS_REGION__@$AWS_REGION@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__ECR_IMAGE__@$REPOSITORY_URL:$IMAGE_TAG@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__LOG_GROUP__@$LOG_GROUP@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__TASK_ROLE__@$TASK_EXECUTION_ROLE@" $TASK_DEFINITION_FILE_NAME
      - sed -ie "s@__EXECUTION_ROLE__@$TASK_EXECUTION_ROLE@" $TASK_DEFINITION_FILE_NAME

      - cat $APP_SPEC_FILE_NAME
      - cat $TASK_DEFINITION_FILE_NAME

artifacts:
  files:
    - $APP_SPEC_FILE_NAME
    - $TASK_DEFINITION_FILE_NAME
