version: '3'

services:
  nodejs:
    build:
      dockerfile: deployment/docker/Dockerfile.nodejs
      context: .
    container_name: nodejsserver
    hostname: nodejsserver
    ports:
      - 8080:8080 
    networks:
      - example-net  

  nginx:
    build:
      dockerfile: deployment/docker/Dockerfile.nginx
      context: .
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80 
      - 443:443 
    depends_on:
      - nodejs
    networks:
      - example-net

networks:
  example-net:
